apiVersion: jvmbuildservice.io/v1alpha1
kind: SystemConfig
metadata:
  name: cluster
spec:
  #This is used to drive the builder image build
  #Versions places here for gradle will be used generate the relevant dockerfiles
  #after you run generate.sh
  builders:
    jdk7:
      tag: jdk:7,maven:3.8.8;3.9.5,ant:1.9.16
    jdk17:
      tag: jdk:8;11;17;21,maven:3.8.8;3.9.5,gradle:8.4;8.3;8.0.2;7.4.2;7.6.3;7.5.1;6.9.2;5.6.4;4.10.3,sbt:1.8.0,ant:1.10.13
